#!/usr/bin/env bash
set -euo pipefail

# ==================================================
# SoftFocus — Canonical Project Bundle Generator
# Phase D / Maintenance Mode
#
# SINGLE authority for bundle structure & meaning.
# Any meaningful change MUST be done here.
# ==================================================

VERSION_FILE="release/VERSION.md"
BUNDLE_DIR="artifacts/bundles"
DATE_UTC="$(date -u +%Y-%m-%d)"
TIME_UTC="$(date -u +%H:%M:%S)"
VERSION="unknown"

fail() { echo "[FAIL] $1" >&2; exit 20; }
info() { echo "[INFO] $1" >&2; }

# --------------------------------------------------
# Resolve version
# --------------------------------------------------
if [ -f "$VERSION_FILE" ]; then
  v="$(grep -E '^version:' "$VERSION_FILE" | awk '{print $2}' || true)"
  [ -n "${v:-}" ] && VERSION="$v"
fi

OUT="$BUNDLE_DIR/project_bundle_${VERSION}_${DATE_UTC}.md"

# --------------------------------------------------
# Canonical document set (ORDER MATTERS)
# --------------------------------------------------
DOCS_REQUIRED=(
  "docs/overview.md"

  "docs/PROJECT_DOCS_HIERARCHY.md"
  "docs/PROJECT_DOCUMENTATION_OVERVIEW.md"

  "docs/control/execution/EXECUTION_5K_NO_DEV.md"
  "docs/control/FINAL_PHASE_D_DECLARATION.md"
  "docs/control/PHASE_D_LOCK_AND_MAINTENANCE.md"
  "docs/control/ALIAS_STATUS_MODEL.md"
  "docs/control/CANONICAL_CI_GATES.md"

  "docs/product/PRODUCT_END_STATE.md"
  "docs/product/runtime/RUNTIME_SPLIT.md"

  "docs/mobile/MOBILE_PRODUCT_SCOPE.md"
  "docs/web/WEB_PRODUCT_SCOPE.md"

  "docs/seo/SEO_ENTRY_INDEX.md"
  "docs/seo/PSEO_CANON.md"
  "docs/seo/ROLE_PAGES_STATUS.md"

  "docs/guides/CANONICAL_EXPLANATIONS_INDEX_RU.md"
)

# --------------------------------------------------
mkdir -p "$BUNDLE_DIR"
: > "$OUT"

for f in "${DOCS_REQUIRED[@]}"; do
  [ -f "$f" ] || fail "Missing required doc: $f"
done

# --------------------------------------------------
{
  echo "# SoftFocus — Project Bundle (Phase D)"
  echo ""
  echo "- Version: $VERSION"
  echo "- Generated: ${DATE_UTC} ${TIME_UTC} (UTC)"
  echo ""
  echo "> Generated by: scripts/bundles/generate_project_bundle.sh"
  echo "> Manual edits are forbidden."
  echo ""
  echo "---"
  echo ""
} >> "$OUT"

emit() {
  echo "==================================================" >> "$OUT"
  echo "FILE: $1" >> "$OUT"
  echo "==================================================" >> "$OUT"
  echo "" >> "$OUT"
  cat "$1" >> "$OUT"
  echo "" >> "$OUT"
}

for f in "${DOCS_REQUIRED[@]}"; do
  emit "$f"
done

cat >> "$OUT" <<'MD'
==================================================
REFERENCE: DISTRIBUTION CONTEXT (NON-CANONICAL)
==================================================

- Role-based pages are distribution artefacts
- No page defines product logic
- All pages resolve to one canonical assessment
- Monetization occurs only post-result

MD

echo "---" >> "$OUT"
echo "_Canonical Phase D bundle._" >> "$OUT"

cp "$OUT" "$BUNDLE_DIR/project_bundle.CURRENT.md"
cp "$OUT" "$BUNDLE_DIR/latest.md"

info "Updated CURRENT and latest pointers"
info "Generated $OUT"
