#!/usr/bin/env bash
set -euo pipefail

# ==================================================
# SoftFocus — Canonical V2 Design-Only Bundle Generator
#
# DESIGN-ONLY / NON-EXECUTABLE
# Does NOT modify Phase D / v1.x bundles.
#
# Single authority for FINAL PRODUCT INTENT (v2).
# ==================================================

VERSION_FILE="release/VERSION.md"
BUNDLE_DIR="artifacts/bundles"
DATE_UTC="$(date -u +%Y-%m-%d)"
TIME_UTC="$(date -u +%H:%M:%S)"
VERSION_LINE="v2-design"
VERSION="unknown"

fail() { echo "[FAIL] $1" >&2; exit 20; }
info() { echo "[INFO] $1" >&2; }

# --------------------------------------------------
# Resolve base version (informational only)
# --------------------------------------------------
if [ -f "$VERSION_FILE" ]; then
  v="$(grep -E '^version:' "$VERSION_FILE" | awk '{print $2}' || true)"
  [ -n "${v:-}" ] && VERSION="$v"
fi

OUT="$BUNDLE_DIR/project_bundle_${VERSION_LINE}_${DATE_UTC}.md"

# --------------------------------------------------
# Canonical DESIGN-ONLY document set
# ORDER MATTERS
# --------------------------------------------------
DOCS_REQUIRED=(
  "docs/mobile/canonical/MOBILE_DESIGN_ETHOS.md"
  "docs/mobile/contracts/MOBILE_RUNTIME_TO_PRODUCT_BINDING.md"
  "docs/mobile/control/MOBILE_CODE_FREEZE_MAP.md"
  "docs/mobile/contracts/MINIMAL_RUNTIME_SHAPE.md"
  "docs/mobile/contracts/DELETION_EXECUTION_PLAN.md"
)


# --------------------------------------------------
# Prepare output
# --------------------------------------------------
mkdir -p "$BUNDLE_DIR"
: > "$OUT"

for f in "${DOCS_REQUIRED[@]}"; do
  [ -f "$f" ] || fail "Missing required design doc: $f"
done

# --------------------------------------------------
# Header
# --------------------------------------------------
{
  echo "# SoftFocus — Project Bundle (V2 · DESIGN_ONLY)"
  echo ""
  echo "- Version Line: v2"
  echo "- Bundle Type: DESIGN_ONLY"
  echo "- Base Version (informational): $VERSION"
  echo "- Generated: ${DATE_UTC} ${TIME_UTC} (UTC)"
  echo ""
  echo "> Generated by: scripts/bundles/generate_v2_design_bundle.sh"
  echo "> Manual edits are forbidden."
  echo "> This bundle introduces NO executable logic."
  echo ""
} >> "$OUT"

emit() {
  echo "==================================================" >> "$OUT"
  echo "FILE: $1" >> "$OUT"
  echo "==================================================" >> "$OUT"
  echo "" >> "$OUT"
  cat "$1" >> "$OUT"
  echo "" >> "$OUT"
}

for f in "${DOCS_REQUIRED[@]}"; do
  emit "$f"
done

# --------------------------------------------------
# GOVERNANCE BOUNDARY (CANONICAL)
# --------------------------------------------------
cat >> "$OUT" <<'MD'
==================================================
GOVERNANCE BOUNDARY (CANONICAL)
==================================================

This bundle defines FINAL PRODUCT DESIGN INTENT
for the next major version line (v2.x).

This bundle is DESIGN-ONLY and NON-EXECUTABLE.

It:
- does NOT modify Phase D / v1.x behavior
- does NOT introduce executable aliases
- does NOT attach to CI
- does NOT authorize implementation

Any implementation based on this bundle
requires a NEW phase declaration
and a NEW executable bundle contract.

MD

# --------------------------------------------------
# RELATION TO PHASE D
# --------------------------------------------------
cat >> "$OUT" <<'MD'
==================================================
RELATION TO PHASE D
==================================================

Phase D (v1.x) remains FINAL, LOCKED, and OPERATIONAL.

This bundle exists in PARALLEL and FUTURE context only.

No document in this bundle:
- overrides v1.x meaning
- alters mobile runtime
- changes UI behavior
- enables monetization changes

Violation of this separation
is a governance breach.

MD

# --------------------------------------------------
# END
# --------------------------------------------------
cat >> "$OUT" <<'MD'
==================================================
END OF BUNDLE
==================================================

_Canonical V2 Design-Only bundle._
MD

info "Generated V2 DESIGN-ONLY bundle: $OUT"

