#!/usr/bin/env bash
set -euo pipefail

# ==================================================
# SoftFocus — Canonical Project Bundle Generator
# Phase D / Maintenance Mode
#
# SINGLE authority for bundle structure & meaning.
# Follows established artifacts/bundles format.
# ==================================================

VERSION_FILE="release/VERSION.md"
BUNDLE_DIR="artifacts/bundles"
DATE_UTC="$(date -u +%Y-%m-%d)"
TIME_UTC="$(date -u +%H:%M:%S)"
VERSION="unknown"

fail() { echo "[FAIL] $1" >&2; exit 20; }
info() { echo "[INFO] $1" >&2; }

# --------------------------------------------------
# Resolve version (expects: version: 1.5.0)
# --------------------------------------------------
if [ -f "$VERSION_FILE" ]; then
  v="$(grep -E '^version:' "$VERSION_FILE" | awk '{print $2}' || true)"
  [ -n "${v:-}" ] && VERSION="$v"
fi

OUT="$BUNDLE_DIR/project_bundle_${VERSION}_${DATE_UTC}.md"

# --------------------------------------------------
# Canonical document set (ORDER MATTERS)
# Phase D = FINAL meaning for v1.x
# --------------------------------------------------
DOCS_REQUIRED=(
  "docs/overview.md"
  "docs/PROJECT_DOCS_HIERARCHY.md"
  "docs/PROJECT_DOCUMENTATION_OVERVIEW.md"

  "docs/control/FINAL_PHASE_D_DECLARATION.md"
  "docs/control/PHASE_D_LOCK_AND_MAINTENANCE.md"
  "docs/control/ALIAS_STATUS_MODEL.md"
  "docs/control/CANONICAL_CI_GATES.md"
  "docs/operations/MAINTENANCE_MODE.md"

  "docs/product/PRODUCT_END_STATE.md"
  "docs/product/runtime/RUNTIME_SPLIT.md"

  "docs/mobile/contracts/MOBILE_PRODUCT_SCOPE.md"
  "docs/mobile/contracts/MOBILE_DISTRIBUTION_ENDPOINT.md"
  "docs/web/contracts/WEB_PRODUCT_SCOPE.md"

  "docs/operations/monetization/MOBILE_MONETIZATION_BINDING.md"

  "docs/seo/SEO_ENTRY_INDEX.md"
  "docs/seo/PSEO_CANON.md"
  "docs/seo/ROLE_PAGES_STATUS.md"

  "docs/guides/CANONICAL_EXPLANATIONS_INDEX_RU.md"
  "docs/operations/status/STATUS.md"
)

# --------------------------------------------------
# Prepare output
# --------------------------------------------------
mkdir -p "$BUNDLE_DIR"
: > "$OUT"

for f in "${DOCS_REQUIRED[@]}"; do
  [ -f "$f" ] || fail "Missing required doc: $f"
done

# --------------------------------------------------
# Header
# --------------------------------------------------
{
  echo "# SoftFocus — Project Bundle (Phase D)"
  echo ""
  echo "- Version: $VERSION"
  echo "- Generated: ${DATE_UTC} ${TIME_UTC} (UTC)"
  echo ""
  echo "> Generated by: scripts/bundles/generate_project_bundle.sh"
  echo "> Manual edits are forbidden."
  echo ""
} >> "$OUT"

emit() {
  echo "==================================================" >> "$OUT"
  echo "FILE: $1" >> "$OUT"
  echo "==================================================" >> "$OUT"
  echo "" >> "$OUT"
  cat "$1" >> "$OUT"
  echo "" >> "$OUT"
}

for f in "${DOCS_REQUIRED[@]}"; do
  emit "$f"
done

# --------------------------------------------------
# NEXT REQUIRED PHASE (DECLARATIVE)
# --------------------------------------------------
cat >> "$OUT" <<'MD'
==================================================
NEXT REQUIRED PHASE (DECLARATIVE)
==================================================

SoftFocus v1.x is COMPLETE and operating in Phase D (Maintenance Mode).

No further development is permitted within this phase.

Any future work MUST occur under a new phase with a new bundle contract.

### Required conditions to leave Phase D

A transition to the next phase (e.g. v2.x) requires ALL of the following:

1. A new phase declaration document
2. A new product axis or expanded analytical scope
3. A new bundle generator contract
4. Explicit invalidation of Phase D immutability
5. New CI gates and audit stages

Without these conditions, any attempt to:
- add features
- modify UX
- expand monetization surfaces
- introduce adaptive behavior

is a governance violation.
MD

# --------------------------------------------------
# PHASE D OPERATIONAL RULE (CANONICAL)
# --------------------------------------------------
cat >> "$OUT" <<'MD'
==================================================
PHASE D OPERATIONAL RULE (CANONICAL)
==================================================

Phase D is a Maintenance and Operation phase.

During Phase D:
- product logic is frozen
- analytical axes are immutable
- UI semantics must not change
- SEO expansion is forbidden
- monetization experiments are forbidden

Allowed actions:
- operational deployment
- distribution via approved channels
- mobile store submission
- bug fixes without semantic impact
- documentation clarification only

Any action that introduces:
- new surfaces
- new interpretations
- new user flows
- expanded SEO entry points

is a governance violation.

To exit Phase D, a new phase declaration
and a new bundle contract are mandatory.
MD

# --------------------------------------------------
# REFERENCE: DISTRIBUTION CONTEXT (NON-CANONICAL)
# --------------------------------------------------
cat >> "$OUT" <<'MD'
==================================================
REFERENCE: DISTRIBUTION CONTEXT (NON-CANONICAL)
==================================================

- Role-based pages are distribution artefacts
- No page defines product logic
- All pages resolve to one canonical assessment
- Monetization occurs only post-result

---
_Canonical Phase D bundle._
MD

# --------------------------------------------------
# Pointers (match existing tree)
# --------------------------------------------------
cp "$OUT" "$BUNDLE_DIR/project_bundle.CURRENT.md"
cp "$OUT" "$BUNDLE_DIR/latest.md"

info "Updated project_bundle.CURRENT.md"
info "Updated latest.md"
info "Generated $OUT"
