#!/usr/bin/env bash
set -euo pipefail

STAGE="stage-1"
AUDIT_FILE="docs/mobile/audit/stage-1.latest.yaml"
CHECKLIST="docs/mobile/MOBILE_UI_AUDIT_CHECKLIST.md"

COMMIT="$(git rev-parse HEAD)"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
CHECKSUM="$(sha256sum "$CHECKLIST" | awk '{print $1}')"
NOW="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

mkdir -p docs/mobile/audit
cat > "$AUDIT_FILE" <<YAML
stage: stage-1
domain: mobile-ui-visual
version: v1

result: PASS

commit: $COMMIT
branch: $BRANCH

path: $CHECKLIST
checksum: $CHECKSUM

reviewed_by: sfctl
reviewed_at: $NOW

notes: |
  Stage-1 visual audit generated automatically.

declaration: >
  This file was generated by scripts/stage-1/run.sh.
  Manual edits are prohibited.
YAML

echo "✅ stage-1 AUDIT: PASS"
